### PR TITLE
update the checklist

### PR DESCRIPTION
**Pull request by szaimen**
As discussed during the Lasercutter examination

### CODE REVIEW

**Comment by szaimen** [comment]
@fabiantheblind could you review this? :)

**Comment by ff6347** [comment]
@szaimen I have not worked with the laser since 2017. I guess I'm the wrong one to ask. Maybe you try to get some feedback from the laser workspace in incom? https://fhp.incom.org/workspace/6508

**Comment by szaimen** [comment]
@ff6347 thanks for the feedback! Yes, I already talked to the person in question but it seems like she is not really used to github. So we'll see if this gets merged. For now, at least the PDF files got updated :)

**Comment by ff6347** [comment]
Maybe ask @sebastian-meier

**Comment by ff6347** [comment]
@szaimen okay. So I'll merge this. Ask someone with admin rights to add you to the contributors maybe

**Comment by ff6347** [comment]
@szaimen The PDF wasn't updated. Only the online version https://fh-potsdam.github.io/the-ultimate-laser-guide/
The PDF needs Pandoc to be generated. I have this workflow that uses pandoc on GitHub actions and commits the result back into the repo. Maybe you can use it as a starting point to update the PDF in the repo. The command to generate the PDF is this one https://github.com/FH-Potsdam/the-ultimate-laser-guide/blob/5eae6ca2b9ea6cb995d45866c579666417fdb133/package.json#L7

**Comment by szaimen** [comment]
@ff6347 thanks for the heads-up! Unfortunatley I don't have a Mac and failed to create the pdf on my machine. 
I had the idea to automatically create the file using github actions but it fails during creation because CamingoCode is not a open source font, afaik.

See https://github.com/szaimen/the-ultimate-laser-guide/blob/master/.github/workflows/create-pdf.yml for the closest I got when trying to create a workflow that automatically creates the pdf file.

**Comment by sebastian-meier** [comment]
Moin,

I am actually at the laser today and will look into this. If its the case and the guide is using a proprietary font, we should switch.

**Comment by ff6347** [comment]
> @szaimen The PDF wasn't updated. Only the online version [fh-potsdam.github.io/the-ultimate-laser-guide](https://fh-potsdam.github.io/the-ultimate-laser-guide/) The PDF needs Pandoc to be generated. I have this workflow that uses pandoc on GitHub actions and commits the result back into the repo. Maybe you can use it as a starting point to update the PDF in the repo. The command to generate the PDF is this one
> 
> https://github.com/FH-Potsdam/the-ultimate-laser-guide/blob/5eae6ca2b9ea6cb995d45866c579666417fdb133/package.json#L7

Sorry. Forgot to link the repo where I had the workflow. You can see it here https://github.com/technologiestiftung/stadtpuls-behind-the-curtain/blob/main/.github/workflows/build.yml

**Comment by ff6347** [comment]
In your case you don't need decktape to build the PDF. You can use pandoc to do this

**Comment by szaimen** [comment]
@ff6347 thanks! Still, I think a proprietary font is used which will probably fail in any case.

**Pull request merged**
